/* generated by 'svelte-accmod' / Svelte vX.Y.Z-1 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

const SOME_CONSTANT = 42;

function foo(bar) {
	console.log(bar);
}

function instance($$self, $$props, $$invalidate) {
	return [foo];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, { foo: 0 });
	}

	get foo() {
		return foo;
	}

	get $cty_config() {
		return {};
	}
}

export default Component;
export { SOME_CONSTANT };