/* generated by 'svelte-accmod' / Svelte vX.Y.Z */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

function instance($$self, $$props, $$invalidate) {
	let { x } = $$props;
	let a;
	let b;

	$$self.$$set = $$props => {
		if ('x' in $$props) $$invalidate(0, x = $$props.x);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*x*/ 1) {
			$: $$invalidate(1, b = x);
		}

		if ($$self.$$.dirty & /*b*/ 2) {
			$: a = b;
		}
	};

	return [x, b];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, null, safe_not_equal, { x: 0 });
	}

	get x() {
		return this.$$.ctx[0];
	}

	set x(x) {
		this.$set({ x });
	}

	get $cty_config() {
		return {};
	}
}

export default Component;